require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'myviroapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ViroReact', :path => './node_modules/react-viro/ios/'
  pod 'ViroKit_static_lib', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/static_lib'

  target 'myviroappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'myviroapp-tvOS' do
  # Pods for myviroapp-tvOS

  target 'myviroapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
